Transform: "AWS::Serverless-2016-10-31"
Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 30
    Environment: 
      Variables:
        CORS_URL: !Ref CorsUrl

Parameters:
  Stage:
    Description: Environment stage
    Type: String
  CorsUrl:
    Description: URL that will be used for CORS
    Type: String
  S3Bucket:
    Description: Bucket that will contain the build artifacts
    Type: String

Resources:
########### Lambda ###########
  LambdaLocalCorsStub:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/options/
      Handler: index.handler
      Role: !GetAtt "iHeartChallengeRole.Arn"
      FunctionName: iHeartLocalCorsHandler
      Timeout: 30
      Events:
        LocalDevelopment:
          Type: Api
          Properties:
            RestApiId: !Ref iHeartChallengeAPI
            Path: /{cors+}
            Method: OPTIONS

################################################
################## Lambdas #####################
################################################

  GetSongs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/songs/standard
      Role: !GetAtt "iHeartChallengeRole.Arn"
      FunctionName: !Sub ${Stage}-get-songs
      Handler: index.handler
      Events:
        API:
          Type: Api
          Properties:
            Path: /songs
            Method: get
            RestApiId: !Ref iHeartChallengeAPI

  GetSongsExtra:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/songs/extra
      Role: !GetAtt "iHeartChallengeRole.Arn"
      FunctionName: !Sub ${Stage}-get-songs-extra
      Handler: index.handler
      Events:
        API:
          Type: Api
          Properties:
            Path: /songs/extra
            Method: get
            RestApiId: !Ref iHeartChallengeAPI

########### API ###########
  iHeartChallengeAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: iHeart-Challenge
      StageName: !Ref Stage
      DefinitionBody:
        Fn::Transform:
          Name: "AWS::Include"
          Parameters:
            Location: !Sub s3://${S3Bucket}/swagger-api-template.json

############### IAM ##############
  iHeartChallengeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
      Policies:
      - PolicyName: !Sub ${Stage}-iHeart-challenge-role
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
      